RayliResearch/AulaVirtualApp/urls.py
from django.urls import path

from . import views

app_name='AulaVirtualApp'
urlpatterns = [
    path('inicio',views.InicioView.as_view(), name="inicio"),
]

RayliResearch/LoginApp/urls.py
from django.urls import path

from . import views

app_name='LoginApp'
urlpatterns = [
    path('login', views.LoginView.as_view(),                  name='login'),
    path('register', views.RegisterView.as_view(),            name='register'),
    path('MisDatos',views.MisDatosView.as_view(),             name='datos'),

]

RayliResearch/RayliApp/urls.py
from django.urls import path

from django.contrib.auth.decorators import login_required
from . import views

app_name='RayliApp'
urlpatterns = [
    path('inicio', views.InicioView.as_view(),                   name='inicio'),
    path('nosotros', views.NosotrosView.as_view(),               name='nosotros'),
    path('servicios', views.ServiciosView.as_view(),             name='servicios'),
    path('servicios/<int:servicio_id>/',views.DetalleServicioView.as_view(),name='detalle_servicio'),
    path('tienda', views.TiendaView.as_view(),                   name='tienda'),
    path('contacto', views.ContactoView.as_view(),               name='contacto'),
    path('capacitacion', views.CapacitacionView.as_view(),       name='capacitacion'),
    path('capacitacion/<int:curso_id>/',views.CursoView.as_view(),name='curso'),
    path('aprende', login_required(views.AprendeView.as_view()),  name='aprende'),
]

RayliResearch/RayliResearch/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.IndexView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('RayliApp/', include('RayliApp.urls')),
    path('AulaVirtualApp/',include('AulaVirtualApp.urls')),
    path('LoginApp/',include('LoginApp.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='LoginApp/login.html'),name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='LoginApp/login.html'),name='logout'),
]

RayliResearch/RayliApp/models.py
from django.db import models

# Create your models here.

class Curso(models.Model):
    nombre          = models.CharField(max_length=100)
    descripcion     = models.TextField()
    precio          = models.FloatField()
    fecha_inicio    = models.DateField()
    fecha_fin       = models.DateField()
    cupos_habiles   = models.IntegerField()

    def __str__(self):
        return self.nombre

class Servicio(models.Model):
    nombre          = models.CharField(max_length=100)
    descripcion     = models.TextField()
    contacto        = models.IntegerField()
    email           = models.EmailField()
    def __str__(self):
        return self.nombre

RayliResearch/RayliApp/views.py
from django.http import HttpResponse

from django.contrib.auth.decorators import login_required
from django.views import View
from django.shortcuts import render, get_object_or_404
from .models import *
class InicioView(View):
	template_name = 'RayliApp/inicio.html'
	context={

	}
	def get(self,request,*args,**kwargs):
		ListServicios=Servicio.objects.all()
		ListCursos=Curso.objects.all()
		self.context['ListServicios']= ListServicios
		self.context['ListCursos']=ListCursos
		return render(request, self.template_name,self.context )
	#def post(self,request,*args,**kwargs):
	
class NosotrosView(View):
	template_name = 'RayliApp/nosotros.html'
	context={

	}
	def get(self,request,*args,**kwargs):
		
		return render(request, self.template_name,self.context )
	#def post(self,request,*args,**kwargs):	

class TiendaView(View):
	template_name = 'RayliApp/tienda.html'
	context={

	}
	def get(self,request,*args,**kwargs):
		
		return render(request, self.template_name,self.context )
	#def post(self,request,*args,**kwargs):	


class ServiciosView(View):
	template_name = 'RayliApp/servicios.html'
	context={

	}
	def get(self,request,*args,**kwargs):
		
		return render(request, self.template_name,self.context )
	#def post(self,request,*args,**kwargs):	

class DetalleServicioView(View):
	template_name = 'RayliApp/detalle_servicio.html'
	context={

	}
	def get(self,request,*args,**kwargs):
		servicio=get_object_or_404(Servicio,pk=kwargs['servicio_id'])
		self.context['servicio']=servicio
		return render(request, self.template_name,self.context )
	#def post(self,request,*args,**kwargs):	
	



class ContactoView(View):
	template_name = 'RayliApp/contacto.html'
	context={

	}
	def get(self,request,*args,**kwargs):
		
		return render(request, self.template_name,self.context )
	#def post(self,request,*args,**kwargs):	


class CapacitacionView(View):
	template_name = 'RayliApp/capacitacion.html'
	context={

	}
	def get(self,request,*args,**kwargs):
		
		return render(request, self.template_name,self.context )
	#def post(self,request,*args,**kwargs):	

class CursoView(View):
	template_name = 'RayliApp/curso.html'
	context={

	}
	def get(self,request,*args, **kwargs):
		curso 			= get_object_or_404(Curso,pk=kwargs['curso_id'])
		self.context['curso']	= curso

		return render(request,self.template_name,self.context )




class AprendeView(View):
	login_required = True
	template_name = 'RayliApp/aprende.html'
	context={

	}
	def get(self,request,*args,**kwargs):
		
		return render(request, self.template_name,self.context )
	#def post(self,request,*args,**kwargs):	


RayliResearch/RayliApp/templates/RayliApp/aprende.html
{% extends "RayliApp/inicio.html" %}
{% load static %}
{% block title %}
    Tienda
{% endblock title %}

{% block body %}
<body>
<div class="">
  <a href="{% url 'AulaVirtualApp:inicio' %}">test</a>
            
</div>        

</body>
{% endblock body %}

RayliResearch/RayliApp/templates/RayliApp/capacitacion.html
{% extends "RayliApp/inicio.html" %}
{%load static%}
{% block title %}
    Capacitación
{% endblock title %}

{% block body %}
<body>
    <div class="ancho80">
        <h2>Nuestros Cursos</h2>
        <div class="separador"></div>
        <div class="tarjetas">
          <a class="tarjeta" href="capacitacion/1">
              <div class="tarj-img" style="background-image: url({%static 'RayliApp/images/cursos/desarrollo.png'%})"></div>
              <div class="tarj-tit">Programación y diseño web</div>
              <div class="tarj-aut">Por Carl Sagan</div>
              <div class="tarj-pre">$20</div>
          </a>
          <a class="tarjeta" href="#">
              <div class="tarj-img" style="background-image: url({%static 'RayliApp/images/GEOGRAFICA.jpg'%})"></div>
              <div class="tarj-tit">Sistemas de información geográfica</div>
              <div class="tarj-aut">Por Carl Sagan</div>
              <div class="tarj-pre">$20</div>
          </a>
          <a class="tarjeta" href="#">
              <div class="tarj-img" style="background-image: url({%static 'RayliApp/images/cursos/aguas.jpg'%})"></div>
              <div class="tarj-tit">Tratamiento de aguas residuales</div>
              <div class="tarj-aut">Por Carl Sagan</div>
              <div class="tarj-pre">$20</div>
          </a>
      </div>
    </div>

</body>
{% endblock body %}

RayliResearch/RayliApp/templates/RayliApp/contacto.html
{% extends "RayliApp/inicio.html" %}
{%load static%}
{% block title %}
    Contacto
{% endblock title %}

{% block body %}
<body>
    <div class="parallax-container mod-parala">
        <div class="parallax"><img src="{%static 'RayliApp/images/fondo-contacto1.jpg'%}"></div>
        <h1 class="white-text titconta">Contáctanos</h1>
    </div>
    <div class="row">
    <div id="contactanos" class="col l10 offset-l1">
        <div class="row">
            <div class="col l8">
                <div class="row">
                    <form class="col s12">
                      <div class="row">
                        <div class="input-field col s6">
                          <input id="first_name" type="text" class="validate" required>
                          <label for="first_name">Nombres</label>
                        </div>
                        <div class="input-field col s6">
                          <input id="last_name" type="text" class="validate" required>
                          <label for="last_name">Apellidos</label>
                        </div>
                      </div>
                      <div class="row">
                        <div class="input-field col s12">
                          <input id="email" type="email" class="validate" required>
                          <label for="email">Email</label>
                        </div>
                      </div>
                      <div class="row">
                        <div class="input-field col s12">
                            <input id="empresa" type="text" class="validate">
                            <label for="empresa">Empresa</label>
                          </div>
                      </div>
                      <div class="row">
                        <div class="input-field col s12">
                            <textarea id="textarea1" class="materialize-textarea" required></textarea>
                            <label for="textarea1">Mensaje</label>
                        </div>
                      </div>
                      <div class="row">
                        <button class="btn-large waves-effect cyan darken-2 right" type="submit" name="action">Enviar
                            <i class="material-icons right">send</i>
                          </button>
                      </div>
                    </form>
                  </div>
            </div>
            <div class="col l4">
              <div class="row">
                <div class="col l10 offset-l1 z-depth-3">
                  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1609.1566407657392!2d-71.57322746419244!3d-16.41257951744039!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9142357dfc4e1dcd%3A0xdd67ae5adf03fbc7!2sCalle%20Miguel%20Grau%2C%20Sachaca%2004013!5e0!3m2!1ses!2spe!4v1617554878145!5m2!1ses!2spe" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                </div>
              </div>
            
            </div>
        </div>
    </div>
    </div>
</body>
{% endblock body %}

RayliResearch/RayliApp/templates/RayliApp/detalle_servicio.html
{% extends "RayliApp/inicio.html" %}
{% load static %}
{% block title %}
  {{servicio.nombre}}
{% endblock title %}

RayliResearch/RayliApp/templates/RayliApp/inicio.html
{%load static%}
<html>
<head>
    
    <title>{% block title %} Rayli App {% endblock title %}</title>
    
    <!--Links a CSS de la pagina RayliApp-->
    <link rel="stylesheet" type="text/css" href="{% static 'RayliApp/css/materialize.min.css'%}" media="screen,projection">
    <link rel="stylesheet" type="text/css" href="{% static 'RayliApp/css/estilos.css'%}">
    {% block estilo_css %}
      
    {% endblock estilo_css %}
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charset="utf-8"/>

    <script type="text/javascript" src="{% static 'RayliApp/js/jquery-3.5.1.js'%}"></script>
    <script type="text/javascript" src="{% static 'RayliApp/js/materialize.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'RayliApp/js/scripts.js'%}"></script>
    {% block script %}
      
    {% endblock script %}
    

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>

{% block nav %}
<div class="navbar-fixed">
<nav class="nav-wrapper row">
    <div class="col  s8 m8 l1 xl3" >
      <a href="#!" class="brand-logo" id="div_logo">
        <img id="logo_img" src="{% static 'RayliApp/images/logos/RayliResearch_Logohor.png' %}"></a>
    </div>
    <div class="col s4 m4 l8 xl7"> 
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="menu nav-wrapper hide-on-med-and-down">
          <li><a href="{%url 'RayliApp:inicio'%}">Inicio</a></li>
          <li><a href="{%url 'RayliApp:nosotros'%}">Nosotros</a></li>
          <li><a href="{%url 'RayliApp:tienda'%}">Tienda</a></li>
          <li><a href="{%url 'RayliApp:servicios'%}">Servicios</a></li>
          <li><a href="{%url 'RayliApp:capacitacion'%}">Capacitación</a></li>
          <li><a href="{%url 'RayliApp:aprende'%}">Aprende +</a></li>
          <li><a href="{%url 'RayliApp:contacto'%}">Contacto</a></li>
      </ul>
    </div> 
    <div class="col l3 xl2 nav-wrapper hide-on-med-and-down" >
      <ul class="menu "> 
        <!-- Dropdown Trigger -->
        <li id="dropdown-size">
{% if user.username %}
          <a class="dropdown-trigger" data-target="dropdown_account" >
            {{user.username}}
            <i class="material-icons left">account_circle</i>
          </a>
        </li>
      </ul>
        <!-- Dropdown Structure -->
        <ul id="dropdown_account" class="dropdown-content">
          <li><a href="{% url 'LoginApp:datos' %}">Mis Datos</a></li>
          <li><a href="{% url 'LoginApp:register' %}">Aula Virtual</a></li>
          <div class="divider"></div>
          <li><a href="{% url 'logout' %}">Cerrar Sesion</a> </li>
        </ul>
{% else %}
          <a class="dropdown-trigger" data-target="dropdown_account" >
            Mi Cuenta
            <i class="material-icons left">account_circle</i>
          </a>
          </li>
          </ul>
          <!-- Dropdown Structure -->
          <ul id="dropdown_account" class="dropdown-content">
          <li><a href="{% url 'LoginApp:login' %}">Identificate</a></li>
          <li><a href="{% url 'LoginApp:register' %}">Registrate</a></li>
          </ul>

{% endif %}        
    </div>
</nav>
</div>


<ul class="sidenav" id="nav-mobile">
  <li>
    <div class="user-view">
      <div class="background"><img src="{% static 'RayliApp/images/office.jpg' %}"></div>
      <a href="#user"><i class="material-icons circle medium">account_circle</i></a>
{% if user.username %}
      <a href="#name"><span class="name" id="nav_info">{{user.username}}</span></a>
      <a href="#email"><span class="email" id="nav_info">{{user.email}}</span></a>
    </div>
  </li>
  <li><a href="{% url 'LoginApp:datos' %}">Mis Datos</a></li>
  <li><a href="{% url 'logout' %}">Cerrar Sesion</a> </li>
{% else %}
      <a href="#name"><span class="name" id="nav_info">Mi Cuenta</span></a>
      <a href="#email"><span class="email" id="nav_info"> </span></a>
    </div>  
  </li>
  <li><a href="{% url 'LoginApp:login' %}">Identificate</a></li>
  <li><a href="{% url 'LoginApp:register' %}">Registrate</a></li>
{% endif %}  
  <div class="divider"></div>
  <li><a href="{%url 'RayliApp:inicio'%}">Inicio</a></li>
  <li><a href="{%url 'RayliApp:nosotros'%}">Nosotros</a></li>
  <li><a href="{%url 'RayliApp:tienda'%}">Tienda</a></li>
  <li><a href="{%url 'RayliApp:servicios'%}">Servicios</a></li>
  <li><a href="{%url 'RayliApp:capacitacion'%}">Capacitación</a></li>
  <li><a href="{%url 'RayliApp:aprende'%}">Aprende +</a></li>
  <li><a href="{%url 'RayliApp:contacto'%}">Contacto</a></li>
</ul>

{% endblock nav %}


{% block body %}

<body>
  
    <div class="row "> 
    <div class="col s12 m12 ">
    <div class="carousel carousel-slider center" style="height:400px !important;">
      <div class="carousel-fixed-item center">
        <a class="waves-effect cyan darken-2 btn-large darken-text-2">Contáctanos</a>
      </div>
      <div class="carousel-item  " href="#one!" >        
          <img class="img-carrousel" src="{% static 'RayliApp/images/panel_inicial.png' %}"></img >     
         
            <h1 class="">Bienvenido a Rayli Research</h1>
            <p class="">Somos una empresa comprometida con el desarrollo tecnológico </p>
          
      </div>
      <div class="carousel-item " href="#two!" >
          <img class="img-carrousel" src="{% static 'RayliApp/images/panel_capacitacion.png' %}"></img >     
          
            <h1 class="">Asesorías en vivo 24/7</h1>
            <p class="">Te asesoramos con nuestros especialistas en Ingeniería y Contabilidad </p>
        
      </div>
      <div class="carousel-item  " href="#three!">
         <img class="img-carrousel" src="{% static 'RayliApp/images/panel_contabilidad.png' %}"></img >    
                 
            <h1 class="">Desarrollo Intelectual y Profesional </h1>
            <p class="">Capacítate con Nosotros en Modo Virtual en Vivo o Modalidad MOOC</p>
        
      </div>
      <div class="carousel-item  " href="#four!" >
        <img class="img-carrousel" src="{% static 'RayliApp/images/panel_campos.png' %}"></img >    
          
            <h1 class="">Compra en nuestra tienda virtual</h1>
            <p class="">Hacemos envíos a Departamentos y Provincias, y al extranjero</p>
          
      </div>
      <div class="carousel-item  " href="#five!" >
        <img class="img-carrousel" src="{% static 'RayliApp/images/panel_proyectos.png' %}"></img >    
              
          <h1 class="">¡Apoyamos ideas de investigación!, </h1>
          <p class="">Con un equipo académico de primer nivel, para alcanzar logros en importantes eventos académicos como</p>
          <p> Conferencias internacionales a través de la presentación de artículos científicos profesionales. </p>
    </div>
    </div>
    </div></div>
    <div class="section valign-wrapper" id="section-dark">
      <div class="row valign">
        <div class="col s12 m10 offset-m1">
          <div class="row">
            <div class="col s12"><h2 class="section-title">Features</h2>
              <div class="separador"></div>
            
          </div>

            <div class="col s12 m6 l4">
              <h4 class="center-align"><i class="medium material-icons" id="icons-features">settings</i></h4>
              <p class="caption">Nuestros Servicios...</p>
            </div>
            <div class="col s12 m6 l4">
              <h4 class="center-align"><i class="medium material-icons" id="icons-features">sentiment_satisfied</i></h4>
              <p class="caption">Especialistas en ...</p>
            </div>
            <div class="col s12 m6 l4">
              <h4 class="center-align"><i class="medium material-icons" id="icons-features">sort_by_alpha</i></h4>
              <p class="caption">Desarrollamos cursos ...</p>
            </div>
            <div class="col s12 m6 l4">
              <h4 class="center-align"><i class="medium material-icons" id="icons-features">swap_vertical_circle</i></h4>
              <p class="caption">Nuestros productos son...</p>
            </div>
            <div class="col s12 m6 l4">
              <h4 class="center-align"><i class="medium material-icons" id="icons-features">tap_and_play</i></h4>
              <p class="caption">Aprende desde cualquier dispositivo</p>
            </div>
            <div class="col s12 m6 l4">
              <h4 class="center-align"><i class="medium material-icons" id="icons-features">track_changes</i></h4>
              <p class="caption">...</p>
            </div>
          </div>
        </div>
      </div>
    </div>  <!-- Paralax -->
  
 


  <div id="servicios">
      <h2>Servicios</h2>
      <div class="separador"></div>
      <div class="row" id="tarjetas">
          <div class="col s12 m6 l4">
              <div class="card">
                <div class="card-image">
                  <img src="{%static 'RayliApp/images/cursos.jpg'%}">
                  <span class="card-title">PROYECTOS DE INVESTIGACIÓN Y CURSOS PROFESIONALES</span>
                </div>
              </div>
          </div>
          <div class="col s12 m6 l4">
              <div class="card">
                <div class="card-image">
                  <img src="{%static 'RayliApp/images//GEOGRAFICA.jpg'%}">
                  <span class="card-title">SERVICIOS PROFESIONALES DE SISTEMAS DE INFORMACIÓN GEOGRÁFICA</span>
                </div>
              </div>
          </div>            
          <div class="col s12 m6 l4">
              <div class="card">
                <div class="card-image">
                  <img src="{%static 'RayliApp/images/obras.jpg'%}">
                  <span class="card-title">OBRAS CIVILES, PROYECTOS CIVILES Y AMBIENTALES</span>
                </div>
              </div>
          </div>
          <div class="col s12 m6 l4 offset-l2">
            <div class="card">
              <div class="card-image">
                <img src="{%static 'RayliApp/images/cursos.jpg'%}">
                <span class="card-title">ASESORÍA CONTABLE Y FINANCIERA</span>
              </div>
            </div>
        </div>
        <div class="col s12 m6 offset-m3 l4">
          <div class="card">
            <div class="card-image">
              <img src="{%static 'RayliApp/images/cursos.jpg'%}">
              <span class="card-title">TIENDA</span>
            </div>
          </div>
      </div>
      
      </div>
  </div>


  </body>  
{% endblock body %}

{% block footer %}
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l3 s12">
        <h5>Contáctanos</h5>
        <div class="row">
          <div class="col l2 m1 offset-m1 s1 offset-s1">
            <i class="material-icons valign-wrapper">add_location</i>
          </div>
          <div class="col s10">
            <h6 class="valign-wrapper">Calle Miguel Grau 102, Sachaca-Arequipa</h6>
          </div>
        </div>
        <div class="row">
          <div class="col l2 m1 offset-m1 s1 offset-s1">
            <i class="material-icons valign-wrapper">add_location</i>
          </div>
          <div class="col s10">
            <h6 class="valign-wrapper">Sucursal: Urba. San Apolinar Mz E, Lote 8, tercera etapa, La Rinconada-Juliaca</h6>
          </div>
        </div>
        <div class="row">
          <div class="col l2 m1 offset-m1 s1 offset-s1">
            <i class="material-icons valign-wrapper">call</i>
          </div>
          <div class="col s10">
            <h6 class="valign-wrapper">+51 926025911</h6>
          </div>
        </div>
        <div class="row">
          <div class="col l2 m1 offset-m1 s1 offset-s1">
            <i class="material-icons valign-wrapper">email</i>
          </div>
          <div class="col s10">
            <h6 class="valign-wrapper">raylicorp@gmail.com</h6>
          </div>
        </div>
      </div>
      <div class="col l3 s12">
        <h5>Redes Sociales</h5>
        <div class="row">
          <div class="col l4 m3 s4 offset-l1 offset-m2 offset-s2"><a href="https://www.facebook.com/" class="prop-btn btn-face"></a></div>
          <div class="col l4 m3 s4 offset-m2"><a href="https://www.instagram.com/" class="prop-btn btn-ins"></a></div>
        </div>
        <div class="row">
          <div class="col l4 m3 s4 offset-l1 offset-m2 offset-s2"><a href="https://www.twitter.com/" class="prop-btn btn-twi"></a></div>
          <div class="col l4 m3 s4 offset-m2"><a href="https://www.linkdln.com/" class="prop-btn btn-link"></a></div>
        </div>
      </div>
      <div class="col l6 s12">
        <h5>Nosotros</h5>
        <p class="text-lighten-1 flow-text left-align">Somos una empresa comprometida con el medio ambiente, proyectos civiles y en la supervisión de los mismos, elaborando planes estratégicos para cada uno de ellos y comprometidos con la capacitación profesional a nivel nacional.</p>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container" id="copyrigth-footer">
      Copyright © 2021 Raily Research - Todos los derechos reservados.
    </div>
  </div>
</footer>  
{% endblock footer %}

</html>

RayliResearch/RayliApp/templates/RayliApp/nosotros.html
{% extends "RayliApp/inicio.html" %}
{%load static%}

{% block title %}
    Nosotros
{% endblock title %}

{% block body %}
<body>
    <div id="nosotros">
      <div class="row">
        <div class="parallax-container mod-para">
            <div class="parallax"><img src="{%static 'RayliApp/images/nosotros.jpg'%}"></div>
        </div>
      </div>
        <div class="row">
          <div class="col s12 cyan darken-3">
            <ul id="tabs-swipe-demo" class="tabs cyan darken-3">
              <li class="tab col s4"><a class="active white-text" href="#test-swipe-1">Nosotros</a></li>
              <li class="tab col s4"><a class="white-text" href="#test-swipe-2">Misión</a></li>
              <li class="tab col s4"><a class="white-text" href="#test-swipe-3">Visión</a></li>
            </ul>
          </div>
          <div id="test-swipe-1" class="col s12 white black-text">
            <h2>Nosotros</h2>
            <div class="separador"></div>
            <p class="p-80">Somos una empresa moderna fundada por un grupo de profesionales arequipeños, comprometidos con el desarrollo del país, de manera sostenible con el medio ambiente, la sociedad y la economía.</p>
          </div>
          <div id="test-swipe-2" class="col s12 white black-text">
            <h2>Misión</h2>
            <div class="separador"></div>
            <p class="p-80">Ser una empresa líder en gestión, para la ejecución de proyectos públicos y privados, asesorías contables, y capacitación profesional en el ámbito académico.</p>
          </div>
          <div id="test-swipe-3" class="col s12 white black-text">
            <h2>Visión</h2>
            <div class="separador"></div>
            <p class="p-80">Nuestra visión a futuro es extender nuestros servicios a nivel latinoamericano, cumpliendo con estándares y exigencias globales, mostrando siempre productos de calidad y en forma sostenible mejorando el ambiente en el que vivimos.</p>
          </div>
      </div>
    </div>

</body>
{% endblock body %}

RayliResearch/RayliApp/templates/RayliApp/servicios.html
{% extends "RayliApp/inicio.html" %}
{% load static %}
{% block title %}
    Tienda
{% endblock title %}

{% block body %}
<body>
<div class="">
    <div class="carousel carousel-slider center">
        <div class="carousel-fixed-item center">
          <a class="btn waves-effect white grey-text darken-text-2">button</a>
        </div>
        <div class="carousel-item  white-text " href="#one!">
            <img class="test" src="{% static 'RayliApp/images/mantenimiento.png' %}"></img >
        </div>
      </div>
            
</div>        

</body>
{% endblock body %}

RayliResearch/RayliApp/templates/RayliApp/tienda.html
{% extends "RayliApp/inicio.html" %}
{% load static %}
{% block title %}
    Tienda
{% endblock title %}

{% block body %}
<body>
<div class="">
    <div class="carousel carousel-slider center">
        <div class="carousel-fixed-item center">
          <a class="btn waves-effect white grey-text darken-text-2">button</a>
        </div>
        <div class="carousel-item  white-text " href="#one!">
            <img class="test" src="{% static 'RayliApp/images/mantenimiento.png' %}"></img >
        </div>
      </div>
            
</div>        

</body>
{% endblock body %}